import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AnimatedFavicon } from "./components/AnimatedFavicon";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Light Of Life",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AnimatedFavicon
          images={[
            "/favicon-frames/frame1.png",
            "/favicon-frames/frame2.png",
            "/favicon-frames/frame3.png",
          ]}
          interval={500}
        />
        {children}
      </body>
    </html>
  );
}
